FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY aes_decrypt.py payload_parser.py sim_app.py ./

EXPOSE 8080

CMD ["python", "sim_app.py"]
