# QEMU has no USB controller — disable USB stack for simulation builds
CONFIG_USB_DEVICE_STACK=n
CONFIG_USB_CDC_ACM=n
CONFIG_UART_INTERRUPT_DRIVEN=n
CONFIG_UART_LINE_CTRL=n

# No UF2 bootloader offset in QEMU
CONFIG_FLASH_LOAD_OFFSET=0x0
CONFIG_FLASH_LOAD_SIZE=0x0
CONFIG_ROM_START_OFFSET=0x0
